[package]
name = "kara-cli"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "kara"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
kara-core = { path = "../kara-core" }
clap = { version = "4", features = ["derive"] }
hound = "3"
libc = "0.2"

[dev-dependencies]
tempfile = "3"
